services:
  web-app:
    build:
      context: .
    volumes:
      - ./clothes_api:/clothes_api
      - static_volume:/clothes_api/staticfiles
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    command: >
      sh -c "gunicorn clothes_api.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  nginx:
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - static_volume:/clothes_api/staticfiles
      - ./nginx:/etc/nginx/conf.d
    restart: always
    depends_on:
      - web-app

volumes:
  static_volume: