# Generated by Django 3.2.9 on 2022-11-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'М'), (2, 'Ж'), (3, 'Унисекс')], null=True),
        ),
    ]
