# Generated by Django 3.2.9 on 2022-11-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20221127_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quality',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Top quality'), (2, 'High quality - AAA +'), (3, '1: 1🤩')], null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'М'), (2, 'Ж'), (3, 'Унисекс')], null=True),
        ),
    ]
