# Generated by Django 3.2.9 on 2022-12-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_item_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_published',
        ),
    ]
