# Generated by Django 3.2.9 on 2022-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0017_rename_key_mediafile_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
