# Generated by Django 3.2.9 on 2022-12-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_telegramadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.IntegerField(unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('favourites', models.ManyToManyField(blank=True, null=True, to='items.Item')),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramAdmin',
        ),
    ]
