# Generated by Django 3.2.9 on 2022-12-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0021_telegramtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtext',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramtext',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
