# Generated by Django 3.2.9 on 2022-12-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
        ('items', '0023_alter_telegramtext_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramText',
        ),
        migrations.DeleteModel(
            name='TelegramUser',
        ),
        migrations.AlterField(
            model_name='item',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, to='telegram.TelegramUser'),
        ),
    ]
