# Generated by Django 3.2.9 on 2023-02-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_auto_20230206_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Муж'), (2, 'Жен'), (3, 'Унисекс')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Top quality'), (2, 'High quality - AAA +'), (3, '1:1🤩')]),
        ),
    ]
