# Generated by Django 3.2.9 on 2022-11-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_auto_20221127_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(1, 'М'), (2, 'Ж'), (3, 'Унисекс')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='quality',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Top quality'), (2, 'High quality - AAA +'), (3, '1: 1🤩')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.category'),
        ),
    ]
