# Generated by Django 3.2.9 on 2022-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20221127_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
