# Generated by Django 3.2.9 on 2023-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20221224_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ManyToManyField(to='items.Brand'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='items.Category'),
        ),
    ]
